### PR TITLE
@user variable

### PR DESCRIPTION
**Pull request by Stawberri**
This is another bit of code I wrote for my own bot but I thought I'd share!

I noticed that twitter_ebooks yells at you if your bot's username doesn't match the one in your script, and then changes it for you anyway. To stop it from yelling at me, I decided to call twitter.user myself first to grab my bot's username. That's a complete waste of one (of 180) api calls, though, so I thought I'd edit twitter_ebooks to actually save a user variable!

This also introduces a new event, on_user_update, an equivalent of which I use extensively in my bot, and it also keeps @user up to date nearly instantly after people update their bots!

### CODE REVIEW

**Comment by mispy** [comment]
keeping the user object around is a good idea! the reason it overrides the name on mismatch is that bots will break horribly otherwise-- they'll start replying to themselves and such. I don't think it should just be a warning

**Comment by Stawberri** [comment]
I didn't do anything about the warning except rephrase it though. :o It still corrects @username.


Well, I guess I did make one change to have it not give a warning if @username started out as an empty string, but I think if people did that they're doing it on purpose to take advantage of how it corrects their @username anyways. :o

**Comment by mispy** [comment]
ah, okies. aside from that:

- lines 308/309 duplicate each other's functionality (I suggest just new_me=nil)
- line 340 has a typo

if you fix those and the tests (provide a stub user object to the test bot somewhere) I can merge :)

**Comment by Stawberri** [comment]
Actually, that duplicate functionality is there in case someone accidentally passes in a random object like a string. Maybe an ArgunentError would be better for that though.

**Comment by mispy** [comment]
thanks stawberri :)

**Pull request merged**
